name: Build & Release signed APK

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Keystore dekodieren → in Projekt-Root
    - name: Decode keystore
      run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > vdrmanager-release.jks

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build signed APK
      run: ./gradlew :de.bjusystems.vdrmanager:assembleRelease
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: de.bjusystems.vdrmanager/build/outputs/apk/release/de.bjusystems.vdrmanager.ng-release.apk
        asset_name: de.bjusystems.vdrmanager.ng-release-${{ github.ref_name }}.apk
        asset_content_type: application/vnd.android.package-archive