name: Build & Release signed APK

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode keystore
      run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > vdrmanager-release.jks

    - name: Grant execute permission to gradlew
      run: chmod +x gradlew

    - name: Build signed APK
      run: ./gradlew :de.bjusystems.vdrmanager:assembleRelease
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: de.bjusystems.vdrmanager/build/outputs/apk/release/de.bjusystems.vdrmanager.ng-release.apk
        name: de.bjusystems.vdrmanager.ng-release-${{ github.ref_name }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
